"""
py2app build configuration for Spackle.

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["spackle.py"]
APP_NAME = "Spackle"
APP_VERSION = "2.0"
ICON_FILE = "Spackle.icns"  # Generated by build_app.sh from the PNG source

OPTIONS = {
    "py2app": {
        "app": APP,
        "iconfile": ICON_FILE,
        "plist": {
            "CFBundleName": APP_NAME,
            "CFBundleDisplayName": APP_NAME,
            "CFBundleIdentifier": "com.github.vuul.spackle-ssh",
            "CFBundleVersion": APP_VERSION,
            "CFBundleShortVersionString": APP_VERSION,
            "NSHighResolutionCapable": True,
            "NSAppleEventsUsageDescription": (
                "Spackle needs to control Terminal.app to open SSH/Telnet sessions."
            ),
        },
        "packages": [],
        "includes": ["tkinter", "tkinter.ttk", "tkinter.messagebox",
                      "tkinter.colorchooser", "tkinter.filedialog"],
    }
}

setup(
    name=APP_NAME,
    app=APP,
    version=APP_VERSION,
    options=OPTIONS,
    setup_requires=["py2app"],
)
